clip: 0.2
exp_id: v02_simple_env_60_reward_proportion
gamma: 0.99
hybrid_residual: true
lr: 0.0002
max_timesteps_per_episode: 150
method_name: baseline
n_updates_per_iteration: 10
output_dir: /root/catkin_ws/src/project_ppo/runs/stage5_hybrid_fast_mask_smoke
render: true
render_every_i: 10
save_freq: 1
seed: null
timesteps_per_batch: 600
